name: Auto Commit to README

on:
  # schedule:
  #   - cron: "0 */2 * * *"   # Runs every 2 hours (UTC)
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update README timestamp
        run: |
          export TZ='Asia/Kolkata'
          echo "Last updated on: $(date)" > README.md

          git config user.name "Thanish Vishaal"
          git config user.email "Thanvish07@users.noreply.github.com"  # or verified email

          git add README.md
          git commit -m "Auto update: $(date)" || echo "No changes to commit"
          git push
